import Head from "next/head";
import HomeNavBar from "../homeNavBar/HomeNavBar";
import BottomNavBar from "../bottomNavBar/BottomNavBar";
import css from "./layout.module.scss";

const Layout = ({ children, products }) => {
  return (
    <div className={css.layout}>
      <Head>
        <title>Online Pharmacy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <HomeNavBar products={products} />
      <div className={css.child}>{children}</div>
      <BottomNavBar />
    </div>
  );
};
export default Layout;
