import Head from "next/head";
import HomeNavBar from "../homeNavBar/HomeNavBar";
import BottomNavBar from "../bottomNavBar/BottomNavBar";
import css from "./layout.module.scss";

const Layout = ({ children }) => {
  return (
    <div className={css.layout}>
      <Head>
        <title>Online Pharmacy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <script src="https://cdn.jsdelivr.net/npm/pace-js@latest/pace.min.js"></script>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/pace-js@latest/pace-theme-default.min.css"
        />
      </Head>
      <HomeNavBar />
      <div className={css.child}>{children}</div>
      <BottomNavBar />
    </div>
  );
};
export default Layout;
